### ISSUE TITLE
Tracking Issue for poise-in-serenity

### ISSUE THREAD

**Issue by GnomedDev** [kangalioo/poise#313]
We are currently trying to merge poise into serenity, to replace the standard framework for 0.13+. This entails quite a bit of rework to make sure that the state of poise matches serenity. This is the issue to track that effort.

# Goals
- Remove as much of poise that is not a command framework as possible
- Remove unmaintained code, or split it off
- Remove as much magic as possible

# Progress
- [x] Remove user data setup (done, serenity-next)
- [x] Remove autocomplete magic (done, next, #312)
- [ ] Audit and cleanup `Command` (allocations, etc)
- [ ] Audit and cleanup `FrameworkOptions`
- [ ] Investigate the Modal derive, and if that should be split off
- [ ] Remove autoref specialisation for command handling, just use traits like everyone else (#320)
- [x] Remove help command infrastructure, should be split out into a separate crate (#323)
- - [ ] Investigate the rest of the builtins
